# Redefining the constraints for Raspberry Pi GPIO pins
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io[0]}]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io[1]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io[2]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io[3]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io[4]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io[5]}]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io[6]}]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io[7]}]
set_property -dict {PACKAGE_PIN W10 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[0]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[1]}]
#set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[2]}]
set_property -dict {PACKAGE_PIN W8 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[2]}]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[3]}]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[4]}]
set_property -dict {PACKAGE_PIN V6 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[5]}]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[6]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports {rpi_gpio_tri_io_o[7]}]

set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports {clk}];
